### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by AlanJSQ** [BlakeHyde/ytkt#2]
I cloned the repo, had to `brew install poetry` to even install.

After install, I didn't see the `ytkt` executable or script and have no idea how to run this against my yaml file.

**Comment by BlakeHyde** [comment]
That's what you get for using things that are extremely unpolished. :)

`poetry run ytkt`

**Comment by BlakeHyde** [comment]
Actually, it turns out that I never added that to the scripts. Fixed by https://github.com/BlakeHyde/ytkt/commit/c528ef4bd03311663a93f0ddf5c59b32fb758a3a.
